pipeline {
    agent any

    environment {
        BRANSH_NAME = 'Master'
        GITHUB_CREDENTIALS_ID = 'github-credentials'
        GITHUB_URL = 'https://github.com/Ahemida96/iVolve-Training.git'
        REGISTRY_USERNAME = "ahemida96"
        REGISTRY_CREDENTIALS_ID = 'dockerhub-credentials'
        IMAGE_NAME = 'webapp'
        K8S_DEPLOYMENT = 'Jenkins/lab3/k8s/webapp-deploy.yaml'
        K8S_SERVICE = 'Jenkins/lab3/k8s/webapp-service.yaml'
        K8S_CRED_ID = 'kubeconfig'
        MINIKUBE_SERVER = "https://192.168.74.138:8443"
    }

    stages {

        stage('Clone Git') {
            steps {
                git branch: BRANSH_NAME,
                    credentialsId: GITHUB_CREDENTIALS_ID,
                    url: GITHUB_URL
            }
        }

        stage("Build & Test Docker Image") {
            steps {
                script {
                    sh 'ls'
                    sh 'docker build -t ${REGISTRY_USERNAME}/${IMAGE_NAME}:${BUILD_ID} Jenkins/lab3/.'
                }
            }
            post {
                success {
                    echo "Image built successfully"
                }
                failure {
                    echo "Image build failed"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: REGISTRY_CREDENTIALS_ID, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'docker login -u ${USERNAME} -p ${PASSWORD}'
                        sh 'docker push ${REGISTRY_USERNAME}/${IMAGE_NAME}:${BUILD_ID}'
                    }
                }
            }
            post {
                success {
                    echo "Image pushed successfully to Docker Hub"
                }
                failure {
                    echo "Image push failed"
                }
            }
        }

        stage('Delete local Docker Images') {
            steps {
                sh 'docker rmi ${REGISTRY_USERNAME}/${IMAGE_NAME}:${BUILD_ID}'
            }
            post {
                success {
                    echo "Local Docker image deleted successfully"
                }
                failure {
                    echo "Local Docker image deletion failed"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    
                    sh "sed -i 's|${REGISTRY_USERNAME}/${IMAGE_NAME}:.*|${REGISTRY_USERNAME}/${IMAGE_NAME}:${BUILD_ID}|g' ${K8S_DEPLOYMENT}"
                    withCredentials([file(credentialsId: "${K8S_CRED_ID}", variable: 'KUBECONFIG')]) {
                        sh "export KUBECONFIG=${KUBECONFIG} && kubectl --server ${MINIKUBE_SERVER}  --insecure-skip-tls-verify=true apply -f ${K8S_DEPLOYMENT}"
                    }
                }
            }
            post {
                success {
                    echo "Deployment successful"
                }
                failure {
                    echo "Deployment failed"
                }
            }
        }

    }
}