apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: devops
  labels:
    name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins
      app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        name: jenkins
        app: jenkins
    spec:
      # restartPolicy: Never
      serviceAccountName: jenkins-admin
      securityContext:
        fsGroup: 1000
        runAsUser: 0

      initContainers:
      - name: install-docker
        image: docker:stable
        command: ["cp", "/usr/local/bin/docker", "/data/docker"]    
        volumeMounts:
        - name: docker
          mountPath: "/data"

      - name: install-kubectl
        image: eslamkarim/jenkins-ansible-kubectl
        command: ["cp", "/usr/local/bin/kubectl", "/data/kubectl"]    
        volumeMounts:
        - name: kubectl
          mountPath: "/data"  

      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          volumeMounts:
            - name: jenkins-home-volume
              mountPath: "/var/jenkins_home"
            - name: jenkins-logs
              mountPath: /var/log/jenkins
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: docker
              subPath: "docker"
              mountPath: "/usr/local/bin/docker"
            - name: kubectl
              subPath: "kubectl"
              mountPath: "/usr/local/bin/kubectl"
      volumes:
        - name: jenkins-home-volume
          persistentVolumeClaim:
            claimName: jenkins-home-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            # type: socket
        - name: docker
          emptyDir: {}
        - name: kubectl
          emptyDir: {}
        - name: jenkins-logs
          emptyDir: {}